"$schema" = "./node_modules/wrangler/config-schema.json"
name = "colormean-project"
main = "custom-worker.js"
compatibility_date = "2026-01-13"
pages_build_output_dir = "out"

compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"